services:
  # Service API (AdonisJS)
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: template-nextgen-api
    ports:
      - "3333:3333"
    env_file:
      - ./server/.env
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  # Reverse Proxy (Nginx) avec fichiers statiques
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: template-nextgen-nginx
    ports:
      - "4444:80"
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
