services:
  # Service API (AdonisJS)
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: template-nextgen-api
    ports:
      - "3333:3333"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - PORT=3333
      - HOST=0.0.0.0
      - LOG_LEVEL=info
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

  # Reverse Proxy (Nginx) avec fichiers statiques
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: template-nextgen-nginx
    ports:
      - "4444:80"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
