[phases.setup]
nixPkgs = ["nodejs", "bun"]

[phases.install]
cmds = [
  "bun install"
]

[phases.build]
cmds = [
  "bun run build",
  "cd server && bun run build",
  "mkdir -p server/public && cp -r client/dist/* server/public/"
]

[start]
cmd = "cd server && bun run start"

[variables]
NODE_ENV = "production"
